export enum TypeDossier {
  SINISTRE_CORPOREL = 'SINISTRE_CORPOREL',
  SINISTRE_MATERIEL = 'SINISTRE_MATERIEL',
  SINISTRE_MORTEL = 'SINISTRE_MORTEL',
  IMMOBILIER = 'IMMOBILIER',
  SPORT = 'SPORT',
  CONTRAT = 'CONTRAT',
  CONTENTIEUX = 'CONTENTIEUX',
  AUTRE = 'AUTRE',
}
